name: Build and Notify

on:
  push:
    branches: ["main"]

jobs:
  build:
    if: "contains(github.event.head_commit.message, '[run-ci]')"
    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

#      - name: Flutter clean
#        run: flutter clean
#
#      - name: Install dependencies
#        run: flutter pub get
#
#      - name: Build dart runners
#        run: dart run build_runner build
#
#      - name: Run Flutter Tests
#        run: flutter test
#
#      - name: Build APK
#        run: flutter build apk --release

      - name: Send APK Release via Mail (SMTP)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          to: mohamed.murad.taha@gmail.com
          subject: Test Email
          body: 'Your APK has been successfully built.'