name: Build and Notify

on:
  push:
    branches: ["main"]

jobs:
  build:
    if: "contains(github.event.head_commit.message, '[run-ci]')"
    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract version number
        id: extract_version
        run: |
          VERSION_NUMBER=$(grep 'version' pubspec.yaml | awk '{print $2}' | tr -d "\'")
          echo "::set-output name=version::$VERSION_NUMBER"

      - name: Flutter clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build dart runners
        run: dart run build_runner build

      - name: Run Flutter Tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Attach APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Generate release date
        id: generate_release_date
        run: |
          RELEASE_DATE=$(date -u +"%Y-%m-%d %H:%M:%S")
          echo "::set-output name=release_date::$RELEASE_DATE"

      - name: Send APK Release via Mail (SMTP)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          to: moh.mourad9519@gmail.com
          cc: amira.osama.anwar0@gmail.com
          subject: "Task Completed: APK Release - Version ${{ steps.extract_version.outputs.version }}"
#          attachments: build/app/outputs/flutter-apk/app-release.apk
          body: |
            Dear Mourad,

            I am writing to inform you that I have successfully completed the Ninjaz task with all features mentioned.

            The APK has been built and is ready for release.
            APK Release Information:
            - Version: ${{ steps.extract_version.outputs.version }}
            - Build Number: ${{ github.run_number }}
            - Release Date: ${{ steps.generate_release_date.outputs.release_date }}

            Unfortunately, I couldn't attach the APK to this email due to Google's message size limits. However, I have manually uploaded the APK to Google Drive for your convenience. You can download the APK using the following link:
            https://drive.google.com/file/d/11Q2voPrcgCEPCfZoj_DyTdejSmQYc0c-/view?usp=sharing
            I opted for this manual method to ensure timely completion within the task deadline.
            
            If you have any questions or require further information, please feel free to contact me.
            
            Thank you for the opportunity.

            Best regards,
            Mohamed Mourad
            mohamed.murad.taha@gmail.com
            https://www.linkedin.com/in/mohammed-mourad/
